# install-services.yml
---
- hosts: loadbalancers
  become: true
  tasks:
    # task 1
    - name: Installing services
      yum: name='httpd' state=present
    # task 2
    - name: Ensure apache starts
      service: name='httpd' state=started  enabled=yes

- hosts: webservers
  become: true
  tasks:
    # task 1
    - name: Installing services
      yum:
        name:
          - "httpd"
          - "php"
        state: present
      # task 2
    - name: Ensure apache starts
      service: name="httpd" state=started  enabled=yes
